# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WBHLearnToSummarize' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WBHLearnToSummarize

  target 'WBHLearnToSummarizeUITests' do
    inherit! :search_paths
    # Pods for testing
  end
     pod 'SDWebImage', '~> 4.2.2'                   #源码下载地址:https://github.com/rs/SDWebImage
     pod 'JZNavigationExtension',      '1.5.0.1'    #源码下载地址:https://github.com/JazysYu/JZNavigationExtension.git
     pod 'Masonry',                    '1.1.0'      #源码下载地址:https://github.com/SnapKit/Masonry
     pod 'HexColors',                  '4.0.0'
end
