# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WBHLearnToSummarize' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WBHLearnToSummarize

  target 'WBHLearnToSummarizeUITests' do
    inherit! :search_paths
    # Pods for testing
  end
    pod 'SDWebImage', '~> 4.2.2' #https://github.com/rs/SDWebImage
end
